Name:           astrofind
# RPM Version cannot contain '-'; beta suffix goes in Release field.
# "0.beta1" sorts BEFORE "1" which is correct pre-release ordering.
Version:        0.9.0
Release:        0.beta1%{?dist}
Summary:        Modern asteroid detection software for citizen science
License:        LicenseRef-PolyForm-NC-1.0
URL:            https://codeberg.org/petrinhu/astrofind

# Source tarball generated by Gitea on tag push:
#   https://codeberg.org/petrinhu/astrofind/archive/v0.9.0-beta.tar.gz
Source0:        %{name}-%{version}-beta.tar.gz

# ── Build dependencies ────────────────────────────────────────────────────
# FetchContent pulls: spdlog, nlohmann/json, SEP, Catch2, CCfits — no devel pkgs needed.
# cfitsio: system package preferred; cmake falls back to FetchContent if missing.
BuildRequires:  cmake >= 3.22
BuildRequires:  ninja-build
BuildRequires:  gcc-c++
BuildRequires:  git
BuildRequires:  pkg-config
BuildRequires:  qt6-qtbase-devel >= 6.4
BuildRequires:  qt6-qtcharts-devel >= 6.4
BuildRequires:  qt6-qtopengl-devel >= 6.4
BuildRequires:  qt6-qt5compat-devel >= 6.4
BuildRequires:  qt6-linguist
BuildRequires:  cfitsio-devel
BuildRequires:  fftw-devel
BuildRequires:  eigen3-devel
BuildRequires:  libarchive-devel
BuildRequires:  mesa-libGL-devel
BuildRequires:  libxkbcommon-devel

# ── Runtime dependencies ──────────────────────────────────────────────────
# FetchContent libs (spdlog, SEP, CCfits, QuaZip) are statically linked — no runtime dep.
Requires:       qt6-qtbase >= 6.4
Requires:       qt6-qtcharts >= 6.4
Requires:       qt6-qt5compat >= 6.4
Requires:       cfitsio
Requires:       fftw >= 3.3
Requires:       libarchive >= 3.5
Requires:       mesa-libGL
Requires:       libxkbcommon

%description
AstroFind is modern asteroid detection software for citizen science and
educational use. Built for Linux, compatible with the IASC / MPC workflow.
Outputs ADES 2022 format (XML and PSV) reports for submission to the Minor
Planet Center.

Features: FITS viewer (SER/XISF/TIFF/PNG), plate solving (astrometry.net /
ASTAP), star detection (SEP), photometry, blink comparison, Moving Object
Detection, calibration (dark/flat/bias), and full bilingual EN/PT-BR interface.

NOTE: This is a beta release. All features are implemented but end-to-end
validation with real telescope FITS files has not yet been performed.

%prep
%autosetup -n %{name}-%{version}-beta

%build
%cmake -GNinja \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=%{_prefix}
%cmake_build

%install
%cmake_install

%check
# Core unit tests (no display required)
%{__cmake_builddir}/bin/astrofind_tests --reporter console || true
# UI tests (offscreen)
QT_QPA_PLATFORM=offscreen %{__cmake_builddir}/bin/astrofind_ui_tests --reporter console || true

%files
%license LICENSE
%doc README.md CHANGELOG.md
%{_bindir}/AstroFind
%{_datadir}/applications/astrofind.desktop
%{_datadir}/icons/hicolor/16x16/apps/astrofind.png
%{_datadir}/icons/hicolor/32x32/apps/astrofind.png
%{_datadir}/icons/hicolor/48x48/apps/astrofind.png
%{_datadir}/icons/hicolor/64x64/apps/astrofind.png
%{_datadir}/icons/hicolor/128x128/apps/astrofind.png
%{_datadir}/icons/hicolor/256x256/apps/astrofind.png
%{_datadir}/icons/hicolor/512x512/apps/astrofind.png

%changelog
* Sat Mar 22 2026 Petrus Silva Costa <petrinhu@astrofind.app> - 0.9.0-0.beta1
- Beta release: all features complete, pending real-world FITS validation
- Version 0.9.0-beta bumped from 0.5.0
- Fixed: invert/flip in blink mode, theme CSS consistency, marking colors
- Added: DPI-proportional sizing (Theme::dp), unified marking color constants
- Fixed: 10 truncated PT-BR translations
